# Generated by Django 3.1.3 on 2020-12-01 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
